INSERT INTO disciplinas (nombre) VALUES('Disciplina A');
INSERT INTO disciplinas (nombre) VALUES('Disciplina B');
INSERT INTO marcas (nombre) VALUES ('Marca A');
INSERT INTO marcas (nombre) VALUES ('Marca B');
INSERT INTO paises (nombre) VALUES ('Argentina');
INSERT INTO paises (nombre) VALUES ('Brasil');
INSERT INTO provincias (nombre,id_pais) VALUES ('Cordoba',1);
INSERT INTO provincias (nombre,id_pais) VALUES ('Santa Fe',1);
INSERT INTO localidades (nombre,id_provincia) VALUES ('Cordoba Capital',1);
INSERT INTO localidades (nombre,id_provincia) VALUES ('Villa de Maria',1);
INSERT INTO roles (nombre) VALUES ('ROLE_USER');
INSERT INTO roles (nombre) VALUES ('ROLE_ADMIN');
INSERT INTO rubros (nombre) VALUES ('Rubro A');
INSERT INTO rubros (nombre) VALUES ('Rubro B');
INSERT INTO rubros (nombre) VALUES ('Rubro C');
INSERT INTO rubros (nombre) VALUES ('Rubro D');
INSERT INTO rubros (nombre) VALUES ('Rubro E');
INSERT INTO rubros (nombre) VALUES ('Rubro F');
INSERT INTO rubros (nombre) VALUES ('Rubro G');
INSERT INTO rubros (nombre) VALUES ('Rubro H');
INSERT INTO rubros (nombre) VALUES ('Rubro I');
INSERT INTO rubros (nombre) VALUES ('Rubro J');
INSERT INTO rubros (nombre) VALUES ('Rubro K');
INSERT INTO rubros (nombre) VALUES ('Rubro L');
INSERT INTO rubros (nombre) VALUES ('Rubro M');
INSERT INTO rubros (nombre) VALUES ('Rubro N');
INSERT INTO rubros (nombre) VALUES ('Rubro O');
INSERT INTO rubros (nombre) VALUES ('Rubro P');

INSERT INTO rubros (nombre) VALUES ('Rubro A');
INSERT INTO rubros (nombre) VALUES ('Rubro B');
INSERT INTO rubros (nombre) VALUES ('Rubro C');
INSERT INTO rubros (nombre) VALUES ('Rubro D');
INSERT INTO rubros (nombre) VALUES ('Rubro E');
INSERT INTO rubros (nombre) VALUES ('Rubro F');
INSERT INTO rubros (nombre) VALUES ('Rubro G');
INSERT INTO rubros (nombre) VALUES ('Rubro H');
INSERT INTO rubros (nombre) VALUES ('Rubro I');
INSERT INTO rubros (nombre) VALUES ('Rubro J');
INSERT INTO rubros (nombre) VALUES ('Rubro K');
INSERT INTO rubros (nombre) VALUES ('Rubro L');
INSERT INTO rubros (nombre) VALUES ('Rubro M');
INSERT INTO rubros (nombre) VALUES ('Rubro N');
INSERT INTO rubros (nombre) VALUES ('Rubro O');
INSERT INTO rubros (nombre) VALUES ('Rubro P');

INSERT INTO rubros (nombre) VALUES ('Rubro A');
INSERT INTO rubros (nombre) VALUES ('Rubro B');
INSERT INTO rubros (nombre) VALUES ('Rubro C');
INSERT INTO rubros (nombre) VALUES ('Rubro D');
INSERT INTO rubros (nombre) VALUES ('Rubro E');
INSERT INTO rubros (nombre) VALUES ('Rubro F');
INSERT INTO rubros (nombre) VALUES ('Rubro G');
INSERT INTO rubros (nombre) VALUES ('Rubro H');
INSERT INTO rubros (nombre) VALUES ('Rubro I');
INSERT INTO rubros (nombre) VALUES ('Rubro J');
INSERT INTO rubros (nombre) VALUES ('Rubro K');
INSERT INTO rubros (nombre) VALUES ('Rubro L');
INSERT INTO rubros (nombre) VALUES ('Rubro M');
INSERT INTO rubros (nombre) VALUES ('Rubro N');
INSERT INTO rubros (nombre) VALUES ('Rubro O');
INSERT INTO rubros (nombre) VALUES ('Rubro P');

INSERT INTO rubros (nombre) VALUES ('Rubro A');
INSERT INTO rubros (nombre) VALUES ('Rubro B');
INSERT INTO rubros (nombre) VALUES ('Rubro C');
INSERT INTO rubros (nombre) VALUES ('Rubro D');
INSERT INTO rubros (nombre) VALUES ('Rubro E');
INSERT INTO rubros (nombre) VALUES ('Rubro F');
INSERT INTO rubros (nombre) VALUES ('Rubro G');
INSERT INTO rubros (nombre) VALUES ('Rubro H');
INSERT INTO rubros (nombre) VALUES ('Rubro I');
INSERT INTO rubros (nombre) VALUES ('Rubro J');
INSERT INTO rubros (nombre) VALUES ('Rubro K');
INSERT INTO rubros (nombre) VALUES ('Rubro L');
INSERT INTO rubros (nombre) VALUES ('Rubro M');
INSERT INTO rubros (nombre) VALUES ('Rubro N');
INSERT INTO rubros (nombre) VALUES ('Rubro O');
INSERT INTO rubros (nombre) VALUES ('Rubro P');

INSERT INTO rubros (nombre) VALUES ('Rubro A');
INSERT INTO rubros (nombre) VALUES ('Rubro B');
INSERT INTO rubros (nombre) VALUES ('Rubro C');
INSERT INTO rubros (nombre) VALUES ('Rubro D');
INSERT INTO rubros (nombre) VALUES ('Rubro E');
INSERT INTO rubros (nombre) VALUES ('Rubro F');
INSERT INTO rubros (nombre) VALUES ('Rubro G');
INSERT INTO rubros (nombre) VALUES ('Rubro H');
INSERT INTO rubros (nombre) VALUES ('Rubro I');
INSERT INTO rubros (nombre) VALUES ('Rubro J');
INSERT INTO rubros (nombre) VALUES ('Rubro K');
INSERT INTO rubros (nombre) VALUES ('Rubro L');
INSERT INTO rubros (nombre) VALUES ('Rubro M');
INSERT INTO rubros (nombre) VALUES ('Rubro N');
INSERT INTO rubros (nombre) VALUES ('Rubro O');
INSERT INTO rubros (nombre) VALUES ('Rubro P');

INSERT INTO rubros (nombre) VALUES ('Rubro A');
INSERT INTO rubros (nombre) VALUES ('Rubro B');
INSERT INTO rubros (nombre) VALUES ('Rubro C');
INSERT INTO rubros (nombre) VALUES ('Rubro D');
INSERT INTO rubros (nombre) VALUES ('Rubro E');
INSERT INTO rubros (nombre) VALUES ('Rubro F');
INSERT INTO rubros (nombre) VALUES ('Rubro G');
INSERT INTO rubros (nombre) VALUES ('Rubro H');
INSERT INTO rubros (nombre) VALUES ('Rubro I');
INSERT INTO rubros (nombre) VALUES ('Rubro J');
INSERT INTO rubros (nombre) VALUES ('Rubro K');
INSERT INTO rubros (nombre) VALUES ('Rubro L');
INSERT INTO rubros (nombre) VALUES ('Rubro M');
INSERT INTO rubros (nombre) VALUES ('Rubro N');
INSERT INTO rubros (nombre) VALUES ('Rubro O');
INSERT INTO rubros (nombre) VALUES ('Rubro P');

INSERT INTO rubros (nombre) VALUES ('Rubro A');
INSERT INTO rubros (nombre) VALUES ('Rubro B');
INSERT INTO rubros (nombre) VALUES ('Rubro C');
INSERT INTO rubros (nombre) VALUES ('Rubro D');
INSERT INTO rubros (nombre) VALUES ('Rubro E');
INSERT INTO rubros (nombre) VALUES ('Rubro F');
INSERT INTO rubros (nombre) VALUES ('Rubro G');
INSERT INTO rubros (nombre) VALUES ('Rubro H');
INSERT INTO rubros (nombre) VALUES ('Rubro I');
INSERT INTO rubros (nombre) VALUES ('Rubro J');
INSERT INTO rubros (nombre) VALUES ('Rubro K');
INSERT INTO rubros (nombre) VALUES ('Rubro L');
INSERT INTO rubros (nombre) VALUES ('Rubro M');
INSERT INTO rubros (nombre) VALUES ('Rubro N');
INSERT INTO rubros (nombre) VALUES ('Rubro O');
INSERT INTO rubros (nombre) VALUES ('Rubro P');

INSERT INTO rubros (nombre) VALUES ('Rubro A');
INSERT INTO rubros (nombre) VALUES ('Rubro B');
INSERT INTO rubros (nombre) VALUES ('Rubro C');
INSERT INTO rubros (nombre) VALUES ('Rubro D');
INSERT INTO rubros (nombre) VALUES ('Rubro E');
INSERT INTO rubros (nombre) VALUES ('Rubro F');
INSERT INTO rubros (nombre) VALUES ('Rubro G');
INSERT INTO rubros (nombre) VALUES ('Rubro H');
INSERT INTO rubros (nombre) VALUES ('Rubro I');
INSERT INTO rubros (nombre) VALUES ('Rubro J');
INSERT INTO rubros (nombre) VALUES ('Rubro K');
INSERT INTO rubros (nombre) VALUES ('Rubro L');
INSERT INTO rubros (nombre) VALUES ('Rubro M');
INSERT INTO rubros (nombre) VALUES ('Rubro N');
INSERT INTO rubros (nombre) VALUES ('Rubro O');
INSERT INTO rubros (nombre) VALUES ('Rubro P'); 
INSERT INTO productos (descripcion,estado,imagen,precio_unitario,servicio,stock,id_disciplina,id_marca,id_rubro) VALUES ('Producto 1',true,'',56.3,true,3,1,1,1);
INSERT INTO productos (descripcion,estado,imagen,precio_unitario,servicio,stock,id_disciplina,id_marca,id_rubro) VALUES ('Producto 2',true,'',24.56,true,0,1,1,1);

